services:
- type: web
name: django-api
env: python
buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
startCommand: gunicorn config.wsgi:application --log-file -
envVars:
- key: SECRET_KEY
generateValue: true
- key: DEBUG
value: "False"
- key: ALLOWED_HOSTS
value: "django-api.onrender.com"
# Si usas Postgres de Render, añade DATABASE_URL automáticamente desde el add-on